export const ProvenanceSource = {
  FARMER_REPORTED: "FARMER_REPORTED",
  AGENT_OBSERVED: "AGENT_OBSERVED",
  GPS_MEASURED: "GPS_MEASURED",
  DOCUMENT: "DOCUMENT",
  COOPERATIVE: "COOPERATIVE",
  SACCO: "SACCO",
  BUYER: "BUYER",
  PROCESSOR: "PROCESSOR",
  AUTHORIZED_FINANCIAL_RECORD: "AUTHORIZED_FINANCIAL_RECORD",
  INSTITUTIONAL_REGISTRY: "INSTITUTIONAL_REGISTRY",
  OTHER_APPROVED_SOURCE: "OTHER_APPROVED_SOURCE",
} as const;

export type ProvenanceSourceValue = (typeof ProvenanceSource)[keyof typeof ProvenanceSource];
