export const SectorId = {
  DAIRY: "dairy",
  BEEF_CATTLE: "beef-cattle",
  SHEEP_GOATS: "sheep-goats",
  POULTRY: "poultry",
  PIGS: "pigs",
  AQUACULTURE: "aquaculture",
  APICULTURE: "apiculture",
  MAIZE: "maize",
  BEANS: "beans",
  RICE: "rice",
  IRISH_POTATO: "irish-potato",
  SWEET_POTATO: "sweet-potato",
  CASSAVA: "cassava",
  WHEAT: "wheat",
  SORGHUM: "sorghum",
  MILLET: "millet",
  GREEN_GRAMS: "green-grams",
  COWPEAS: "cowpeas",
  PIGEON_PEAS: "pigeon-peas",
  GROUNDNUTS: "groundnuts",
  SUNFLOWER: "sunflower",
  SUGARCANE: "sugarcane",
  COTTON: "cotton",
  PYRETHRUM: "pyrethrum",
  TEA: "tea",
  COFFEE: "coffee",
  AVOCADO: "avocado",
  MACADAMIA: "macadamia",
  BANANA: "banana",
  MANGO: "mango",
  CITRUS: "citrus",
  COCONUT: "coconut",
  CASHEW: "cashew",
  TOMATO: "tomato",
  ONION: "onion",
  KALE_COLLARDS: "kale-collards",
  CABBAGE: "cabbage",
  CAPSICUM: "capsicum",
  WATERMELON: "watermelon",
  FRENCH_BEANS: "french-beans",
  LIVESTOCK_MEAT: "livestock-meat",
  HORTICULTURE: "horticulture",
} as const;

export type SectorIdValue = (typeof SectorId)[keyof typeof SectorId];

